services:
  - type: web
    name: contact-management-app
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false